### ISSUE TITLE
A Better way to keep track of permitted users

### ISSUE THREAD

**Issue by HaydenMeloche** [AlphaConsole/AlphaConsoleBot#148]
A better way to have the bot keep track of users who have blacklisted titles rather than bothering LegoBased to update the list.

Open for discussion/suggestions.

**Comment by ThePjpollie** [comment]
Maybe something like `!report <DiscordID>` for Staff.
Then in whatever channel (like `#title-reporting`) the bot will post all the stuff by itself fetching from the db.
Where an Admin+ can respond with ✅ to add the report to the `Granted access to blacklisted titles`.
They can also respond with ❌ where it will DM the user that added the reaction all the words where he can easily blacklist them.  (Refer to **Example** to understand what I mean). After blacklisting the bot can automatically reset the title of the user.

__Example:__
If the user had the title: `RLCS Season 69 World Champion` and he got reported by staff.
Cole then adds ❌ to the report and the bot will send this as DM/:

```
Please provide me all the numbers of the words to blacklist (with spaces in between)
- 0. RLCS
- 1. Season
- 2. 69
- 3. World
- 4. Champion
```

Where then cole can answer with: `0 4` and this will blacklist `RLCS` & `Champion`.
Not much effort by the Admins to add new words from reports.

Just an idea, feedback welcome :)

**Comment by coledeb** [comment]
That would actually be pretty nice.  I feel like having it automated like warnings are now would be cool as well, like first time blacklist is 1 day, second time 1 week, etc.

**Comment by coledeb** [comment]
If a user was put on the blacklist, their title would need to be set to blank and the color to 0 for the duration of that, and then they are free to change it after the role is gone. Right now the blocking of users from the channel is entirely dependent on having no discord perms to type in `#set-title` rather than anything to do with the bot. Perhaps while doing this we could also change the blacklist system to be contained within the bot (like the 5m limit between posts in suggestions and showcase) rather than relying on role dependencies.

**Comment by ThePjpollie** [comment]
Will be closing due to innactivity. Will re-open if new suggestions comes up.
